### ISSUE TITLE
ConnectionsList.xml denied for installed applications

### ISSUE THREAD

**Issue by rappen** [MscrmTools/MscrmTools.Xrm.Connection#10]
When using McTools.Xrm.Connection.dll version 1.2016.3.29 with a program installed using msi installer, it is not possible to access the MscrmTools.ConnectionsList.xml file.
Starting the connection selector dialog displays this:

![image](https://cloud.githubusercontent.com/assets/2572253/14274029/38843a26-fb0f-11e5-8540-23751485df3d.png)

Error details:
```System.Exception: Error while serializing: Access to path C:\Program Files\Cinteros AB\Cinteros CRM Deployer\MscrmTools.ConnectionsList.xml is denied.
   vid McTools.Xrm.Connection.XmlSerializerHelper.SerializeToFile(Object o, String path)
   vid McTools.Xrm.Connection.ConnectionsList.Save()
   vid McTools.Xrm.Connection.WinForms.ConnectionSelector.tscbbConnectionsFile_SelectedIndexChanged(Object sender, EventArgs e)```

Related to #2.

**Comment by MscrmTools** [comment]
I guess this problem is more a security access. I guess your installer should handle the possibility to access the folder with read/write privileges

**Comment by rappen** [comment]
It definitely is a security issue, as users normally don't have write access to Program Files folders where applications are installed.
That is why I introduced the possibility to use an alternate path for the Connections in PR https://github.com/MscrmTools/XrmToolBox/pull/262
This makes it possible to have applications working "properly" with storage under AppData instead of Program Files folder.
Perhaps it could be implemented so that if a specific path to the connection file is given, it will not try to write connectionlist file from current folder?
And some fault tolerance when writing the connectionlist file, så that it will simply not be written if not allowed?
If you accept these suggestions, I can try to create a PR for it.

**Comment by MscrmTools** [comment]
Back to the connection project. Ready to receive a PR on this subject

**Comment by MscrmTools** [comment]
@rappen ping :)

**Comment by MscrmTools** [comment]
No need for a PR, I finally understood what you were looking for :)

I added a static property `ConnectionsListFilePath` in singleton `ConnectionsList` so that you can tell the connection controls to store the connections list to a specific file. If the file does not exists, it is created with a default connections file.

```C#
ConnectionsList.ConnectionsListFilePath = "c:\\Temp\\test_local_connectionsList.xml";
ConnectionManager.ConfigurationFile = "BlaBla.xml";
```
