### ISSUE TITLE
Error	: AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.

### ISSUE THREAD

**Issue by MattHorvay** [MscrmTools/MscrmTools.Xrm.Connection#100]
Trying to connect XrmToolBox v.1.2019.11.35 to Dynamics 365 using a user account with MFA. Can't use app passwords because they aren't compatible with Azure AD Conditional Access.

When I use a connection string I get the following error messages:

Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	11/19/2019 2:28:20 PM  Initialize CRM connection Started - AuthType: OAuth
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	11/19/2019 2:28:20 PM  Direct Login Process Started
....
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	11/19/2019 2:28:21 PM  ObtainAccessToken - PROMPT - Behavior: Auto
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	11/19/2019 2:28:22 PM  ERROR REQUESTING Token FROM THE Authentication context - General ADAL Error
Source	: Microsoft.IdentityModel.Clients.ActiveDirectory
Method	: MoveNext
Error	: AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.

I followed the various tutorials I found on how to connect using a connection string.
Any help with this error would be greatly appreciated.

I also tried connecting using the Connection wizard for CRM online option and got a different error message so I'm going to create a different issue for that.

Thank you.

**Comment by RSTSi** [comment]
I've had the same error as you, and I've found this solution that's worked for me:

New Connection → SDK Control → Open SDK Login Control
Choose Office 365, click Show Advanced, choose your region, chuck your details in.

It prompted me for multi-factor authentication, but once I accepted everything, I got in right away.

Hopefully this works for you.
