### ISSUE TITLE
Method not found during connection

### ISSUE THREAD

**Issue by eleung83** [MscrmTools/MscrmTools.Xrm.Connection#109]
I've just updated the Toolbox to v1.2020.2.36 and when I attempt to use one of the stored CRM connections that I had used the previous day I'm getting the following error:

![image](https://user-images.githubusercontent.com/26326026/73827794-18196380-47f8-11ea-8037-8c1f9cf0d05f.png)

Rolling back to v1.2019.11.35 I can use the same CRM connections

**Comment by MscrmTools** [comment]
Ok, I don't why yet but it seems the version of the Mscrm.Xrm.Connection is not the appropriate one... Can you check the version of this dll in your XrmToolBox folder?

**Comment by eleung83** [comment]
I've manually downloaded the latest version from the website, and copied over the existing installation. I can't see a dll for Mscrm.Xrm.Connection. There is a dll for McTools.XrmConnection.

The version of this dll is 1.2020.1.29

![image](https://user-images.githubusercontent.com/26326026/73840137-6be37700-480f-11ea-917a-3655c2acd0de.png)

**Comment by MscrmTools** [comment]
Yes, sorry for that, you checked the appropriate file.
So this version do contains the method not found... so I can't see why you get this error...
Can you try with a fresh installation?

**Comment by rappen** [comment]
Could it be MS SDK not updated properly?
It complains about a method in an SDK class.

**Comment by MscrmTools** [comment]
ah! yes @rappen is right here! What is the version of the Microsoft.Xrm.Tooling.Connector.dll assembly?

**Comment by eleung83** [comment]
![image](https://user-images.githubusercontent.com/26326026/73841639-e8c42000-4812-11ea-9fca-97eb18988d29.png)

Looks like it's the same version as the one used in the PluginRegistration Tool from MS own nuget package although they have different file sizes

**Comment by MscrmTools** [comment]
Sorry (again, not easy to work and answer open source projects), what is the version of Microsoft.Xrm.Sdk.dll ?

**Comment by eleung83** [comment]
9.0.43.1020

**Comment by eleung83** [comment]
If it helps I just manually downloaded the latest toolbox zip file from the website and overwrote all of the files in my local folder

**Comment by rappen** [comment]
Double checking: did you unblock the zip file before unpacking?

**Comment by eleung83** [comment]
yes, they're all unblocked

**Comment by eleung83** [comment]
Found out what the issue could be. It looks like some group policy has installed older versions of CRM Sdk dlls into the GAC_MSIL folder on our machines which causes the conflicts

**Comment by MscrmTools** [comment]
Ah ah!!! I was thinking about this! This has to be the issue yes
