### ISSUE TITLE
Need details to submit to company security centre to allow plugin installation

### ISSUE THREAD

**Issue by Nathanius42** [MscrmTools/MscrmTools.Xrm.Connection#110]
Hello,

I need to submit a request to get various URLs for the XRM toolbox to function whitelisted and added to our proxy file or both. This centres around 2 issues

1. Plugin installation and update blocked
![image](https://user-images.githubusercontent.com/11289018/74285935-7bfcd880-4d72-11ea-9630-ef4565a7ca1d.png)

2. Tool update blocked
![image](https://user-images.githubusercontent.com/11289018/74285963-93d45c80-4d72-11ea-935c-3ac89831e051.png)

What should I be asking to be unblocked specifically for these two functions to work?

Thank you

**Comment by MscrmTools** [comment]
Hi!
XrmToolBox uses only three urls:
- [https://www.xrmtoolbox.com](https://www.xrmtoolbox.com) to retrieve a list of available plugins
- [https://packages.nuget.org/api/v2](https://packages.nuget.org/api/v2) to retrieve plugin package
- [https://github.com/MscrmTools/XrmToolBox/releases/download](https://github.com/MscrmTools/XrmToolBox/releases/download) to download XrmToolBox updates
