### ISSUE TITLE
MFA connection issue

### ISSUE THREAD

**Issue by MitchMilam** [MscrmTools/MscrmTools.Xrm.Connection#112]
So I added the Connection component to one of my applications, mainly to use the SDK Login Dialog for MFA login.  On my main development computer, it works fine.

On another computer, I get

You don't have permission to access any of the organizations in the Microsoft Common Data Service region that you specified. If you're not sure which region your organization resides in, choose "Don't know" for the CDS region and try again. Otherwise check with your CDS administrator.

On that same computer, I can connect both the XrmToolbox and Plugin Registration Tool, using the SDK Login Dialog without issue.

Any idea what it could be?

I am betting a DLL version mismatch or something, but I'm not sure.

Thanks, Mitch

**Comment by MscrmTools** [comment]
Hi @MitchMilam, sorry for the delay to answer...
I have really no idea on how to handle this but if your point is to use MFA, you should connect using the Oauth/MFA connection method in latest version of the connection controls.
