### ISSUE TITLE
Connections and passwords being saved without choosing to save

### ISSUE THREAD

**Issue by sundvl** [MscrmTools/MscrmTools.Xrm.Connection#115]
When adding a new connection, I am leaving the 'Save password' checkbox unchecked, but the password is still being saved.  Additionally, if I am currently connected to an organization, and change connections by adding a new connection using the control in the lower left, the connection AND credentials are being saved without me naming the connection or choosing to save the password.
![image](https://user-images.githubusercontent.com/60792275/80221362-69204300-8602-11ea-85fe-d26c1b6fdf18.png)

**Comment by MscrmTools** [comment]
Thank you for reporting this issue. I will review this problem
