### ISSUE TITLE
OAuth AppId secret is saved in plaintext in connections file

### ISSUE THREAD

**Issue by codes4pizza** [MscrmTools/MscrmTools.Xrm.Connection#116]
I've just updated to latest release (v1.2020.4.38) and tried to create a new connection using the clientid/secret option in the connection wizard. The connection was defined successfully and saved in the default connections. When trying to connection to D365 I got an error reported from ADAL "No redirectUri was configured. ADAL does not provide any defaults."

Eventually i checked to see what was in the connections file and the ReplyUrl element contained the app secret in plaintext.

**Comment by MscrmTools** [comment]
You need to define a redirection url in your Azure AD app (in authentication tab).

I did try the same scenario than you and the password is not stored in the connection file... Moreover, when using client id and secret, the connection item should not contain a ReplyUrl element

Can you send a screenshot (with sensitive values masked) of where you see that?

**Comment by codes4pizza** [comment]
Fully agree with your statement about client id and secret not needing a replyurl and that is what surprised me when xrm toolbox failed to connect and i looked in the connections file. I have just created a brand new connections file to try this and i also could not repro the issue and i have tried a few times with different options, going back and forth etc.

I am wondering if it was an intermittent AD sync problem because at the time i created a new app id and secret in Azure AD and then immediately switched to xml toolbox and tried to use it.
