### ISSUE TITLE
No redirectUri was configured

### ISSUE THREAD

**Issue by icemokka** [MscrmTools/MscrmTools.Xrm.Connection#117]
Hi,

Since version 1.2020.4.38, I'm unable to connect to our D365 Online instance.
I'm using a clientid/secret combination, tried recreating the connection in the new version but same issue.
I'm able to create the connection and give it a name, so no issue there.
But once you want to open the connection (manually of via opening a new tool window) I get a general ADAL error.

![image](https://user-images.githubusercontent.com/28389613/80482248-28069680-8954-11ea-874a-3b2f3cf2c1d9.png)

I think this might be a bug in the latest version.

UPDATE : This issue appears to be a local issue, it's working on another VM of mine.

**Comment by MscrmTools** [comment]
Are you sure your Azure AD app is properly configured with a reply url?
I just tried Client ID/Secret connection and everything worked fine on my side.
I close this issue since you mentioned it was a local issue. 
You can reopen it if needed

**Comment by icemokka** [comment]
Hi,

it is a local issue indeed because the same Azure AD app is working on another instance (in the same tenant).
Not a XrmToolbox bug ...
