### ISSUE TITLE
XrmToolBox Updates Connection File Incorrectly and Improperly

### ISSUE THREAD

**Issue by jzserai** [MscrmTools/MscrmTools.Xrm.Connection#119]
XrmToolBox version 1.2020.2.37
Every time XrmToolBox access the connection file, it changes UseIfd to false and inserts the encrypted password.
This happens in the connection wizard and when actually connecting.

This can be duplicated by manually editing the file in NotePad. Set UseIfd to true and remove the password entirely. Save the file and open XrmToolBox.
Open File Explorer and select the connection file with preview on.
Click the Connect button.
You are prompted to enter your password. Leave Save Password check box unchecked.
Click OK.
XrmToolBox connects to your organization.
The connection file is immediately altered as stated earlier. File Explorer preview will reset as it is altered.
Immediately click the Connect button.
XrmToolBox does not prompt for a password and the connection attempt fails.
From the Configuration menu, select Manage connections.
Select the connection and click the edit button. The first dialog should be correct. Click Next.
On the Internet Facing Deployment settings dialog, notice the No radio button is now selected.
The Home Realm Url is visible, but read-only.
Select the Yes radio button and click Next.
On the User Credentials dialog, notice the password is filled in and the Save password ... check box is unchecked.
Click Next.
Click Yes to test the connection. The connection is successfully validated. Click Finish.
Select the connection and click the edit button again. Click Next.
Notice the No radio button is now selected.

**Comment by MscrmTools** [comment]
@jzserai ok, I think I found the issue.
Could you test your scenario with the following files (just unzip them in your XrmToolBox installation folder)
[McTools.Xrm.Connection.WinForms.zip](https://github.com/MscrmTools/MscrmTools.Xrm.Connection/files/4610270/McTools.Xrm.Connection.WinForms.zip)

**Comment by MscrmTools** [comment]
Should be solved. Please reopen if needed
