### ISSUE TITLE
Save as.... connection file

### ISSUE THREAD

**Issue by rappen** [MscrmTools/MscrmTools.Xrm.Connection#12]
It would be great to be able to save all currently loaded connection to a new file.
Usually the default connection file contains a lot of connections, and if you want to separate them into project/customer dependent connections you would have to create a new file and then create the connections all over.

**Comment by MscrmTools** [comment]
I had added more :) You can also select connections to move to an existing file, as creating a new file already exists.
But I added your suggestion too
