### ISSUE TITLE
Client Secret connection type no longer working.

### ISSUE THREAD

**Issue by AntonioRomera** [MscrmTools/MscrmTools.Xrm.Connection#121]
Ever since I've updated to v1.2020.4.38 The connections that I use with client/secret are no longer working throwing the following error whenever I try to connect

![image](https://user-images.githubusercontent.com/18742653/81926161-8f0c8800-95af-11ea-89b6-9fee8900b1fc.png)

I've checked and compared the connection XML File using a previous version on which it's working properly and noticed the following differences:

Connection XML from 1.2020.2.36
- ServerPort tag is missing
- S2SClientSecret is there
![image](https://user-images.githubusercontent.com/18742653/81928069-af8a1180-95b2-11ea-99d5-33c8a111349d.png)

Connection XML from 1.2020.4.38
- ServerPort tag is there
- S2SClientSecret is missing.
![image](https://user-images.githubusercontent.com/18742653/81928088-bd3f9700-95b2-11ea-887f-40b81b012feb.png)

**Comment by MscrmTools** [comment]
This is a known issue that should be fixed in upcoming release.
But the S2SClientSecret is removed and replace with a new property ClientSecret.
You may have to update your connection to store the secret again

**Comment by MscrmTools** [comment]
Should be fixed now
