### ISSUE TITLE
Error: Invalid Login Information 

### ISSUE THREAD

**Issue by manishkk81** [MscrmTools/MscrmTools.Xrm.Connection#122]
I am getting below error while connecting to CRM using XRMTOOLBOX using ver 1.2019.7.34. It was working till yesterday.
---------------------------
Error
---------------------------
Invalid Login Information : An unsecured or incorrectly secured fault was received from the other party. See the inner FaultException for the fault code and detail.

An unsecured or incorrectly secured fault was received from the other party. See the inner FaultException for the fault code and detail. => Authentication FailureUnable to Login to Dynamics CRM

Unable to Login to Dynamics CRM
---------------------------
OK   
---------------------------

**Comment by MscrmTools** [comment]
Then the problem is on your side if nothing changed on XrmToolBox. Please note that you have an outdated version and you should update to latest one to connect to online environments.
