### ISSUE TITLE
Alphabetizing connection files

### ISSUE THREAD

**Issue by akaskela** [MscrmTools/MscrmTools.Xrm.Connection#124]
The connection files are in alphabetical order in the connections manager, but not in the quick connect menu available in the bottom left (which I just found out about and LOVE).

![image](https://user-images.githubusercontent.com/37714318/84579743-85d52d80-ad9e-11ea-9f33-342d80fb66ba.png)

**Comment by MscrmTools** [comment]
Fixing this right now
