### ISSUE TITLE
System.MissingMethodException: Method not found

### ISSUE THREAD

**Issue by sfagen** [MscrmTools/MscrmTools.Xrm.Connection#125]
One of our users is getting the following error:

![image](https://user-images.githubusercontent.com/29854112/88313780-3f45ed80-ccd1-11ea-9e3f-450b7a90506b.png)

He can log into XRM from another computer, but on his computer he's unable to log in.

Thanks.

**Comment by MscrmTools** [comment]
The cause is old sdk assemblies that must be in the GAC of this computer

**Comment by sfagen** [comment]
Global assembly cache has quite a few assemblies in it, is there a list of required assemblies so I can figure out which one needs to be updated? It was working before the latest version of the XRMToolbox.

**Comment by MscrmTools** [comment]
Latest version of XrmToolBox uses latest version of dynamics 365 sdk assemblies. And these assemblies add new method.
As GAC assemblies are loaded first, XrmToolBox cannot find the method.
This is generally a bad idea to store d365 sdk assemblies in cache.
So remove every Microsoft.xrm and Microsoft.crm assemblies from the GAC and you should be good

**Comment by sfagen** [comment]
We don't have either Microsoft.xrm or Microsoft.crm assemblies in the gac. See attached.

![image](https://user-images.githubusercontent.com/29854112/88341793-7e893400-ccfb-11ea-94db-4dcc52297660.png)

![image](https://user-images.githubusercontent.com/29854112/88341815-8517ab80-ccfb-11ea-8c60-eeedcbb83aa1.png)


Thank you for your help in this!

**Comment by MscrmTools** [comment]
Yes you have 😁

There is another place where the GAC content is visible.

I can't tell you where because I'm not in front of a computer right now but I assure you these files are somewhere
