### ISSUE TITLE
Cannot connect to CRM 8.2 since updated to version 1.2021.1.44

### ISSUE THREAD

**Issue by AntonSul** [MscrmTools/MscrmTools.Xrm.Connection#129]
Hi
Since updating to version 1.201.1.44 one cannot connect to CRM 8.2 as it seems that sdkversion=9 is added to the connection sting automatically when connecting.

Anton

![image](https://user-images.githubusercontent.com/77435584/104569549-a679a480-5659-11eb-9fdf-1dbf4d194c87.png)

**Comment by MscrmTools** [comment]
The error message does not seem related to "sdkversion=9" 

a 404 error indicates a page not found and sdkversion=9 is just a parameter, not the url so 404 error shouldn't be related

**Comment by AntonSul** [comment]
Hi
Sorry. After further investigation I think what is happening.
We have got an On-Premise with IFD installation and it seems that the url that xrmtoolbox uses contains the ORGNAME (https://<servername>/<orgname>/XRMServices/2011/Organization.svc?wsdl&sdkversion=9 as part of the url which is causing the problem.

**Comment by MscrmTools** [comment]
it seems more likely, yes.
Just update your connection and you should be good
