### ISSUE TITLE
Method not found error. setting up new (first) Client ID / Secret connection in MFA cloud environment.

### ISSUE THREAD

**Issue by ChasFor** [MscrmTools/MscrmTools.Xrm.Connection#134]
I'm using XRMToolbox Version 1.2021.2.45

I followed these notes to setup an XRMToolBox connection to Dynamics365: https://jamesdiekman.com/connect-xrm-toolbox-to-an-mfa-enabled-tenant/
I then tried to connect to Dynamics 365 via
New Connection - Client ID/ Secret - Connect - Error (Connection Failed .... method not found .....)

The extract from the log is below ,I hope you can help.

Thanks, 
Charles

Microsoft.Xrm.Tooling.Connector.CrmServiceClient
	Verbose	16	29/03/2021 9:17:09 AM  Initialize CRM connection Started - AuthType: ClientSecret
	Verbose	16	29/03/2021 9:17:09 AM  Direct Login Process Started
	Information	8	29/03/2021 9:17:09 AM  Attempting to Connect to Uri https://xxx.crmx.dynamics.com/XRMServices/2011/Organization.svc
	Verbose	16	29/03/2021 9:17:09 AM  DiscoveryServer indicated organization service location = https://xxx.crmx.dynamics.com/XRMServices/2011/Organization.svc
	Information	8	29/03/2021 9:17:09 AM  Organization Service URI is = https://xxx.crmx.dynamics.com/XRMServices/2011/Organization.svc
	Verbose	16	29/03/2021 9:17:09 AM  ConnectAndInitCrmOrgService - Initializing Organization Service Object
	Information	8	29/03/2021 9:17:09 AM  ConnectAndInitCrmOrgService - Requesting connection to Organization with CRM Version: No organization data available
	Information	8	29/03/2021 9:17:09 AM  AuthenticateService - found authority with name https://login.microsoftonline.com/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/
	Information	8	29/03/2021 9:17:09 AM  AuthenticateService - found resource with name https://xxx.crmx.dynamics.com/
	Verbose	16	29/03/2021 9:17:09 AM  ObtainAccessToken - Client Secret
	Verbose	16	29/03/2021 9:17:10 AM  Added WebClient Header Hooks to the Request object.
	Information	8	29/03/2021 9:17:10 AM  ConnectAndInitCrmOrgService - Proxy created, total elapsed time: 00:00:01.3259511
	Error	2	29/03/2021 9:17:10 AM  Unable to connect to CRM: Method not found: 'System.String Microsoft.Xrm.Sdk.Organization.OrganizationDetail.get_EnvironmentId()'.
Source	: Microsoft.Xrm.Tooling.Connector
Method	: RefreshInstanceDetails
Date	: 29/03/2021
Time	: 9:17:10 AM
Error	: Method not found: 'System.String Microsoft.Xrm.Sdk.Organization.OrganizationDetail.get_EnvironmentId()'.
Stack Trace	: at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.RefreshInstanceDetails(IOrganizationService crmService, Uri uriOfInstance)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DoDirectLogin(Boolean IsOnPrem)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()

**Comment by MscrmTools** [comment]
This issue indicates you are using older version of the SDK. If you are using latest version of XrmToolBox, then it means you have older version of the SDK in your Global Assembly Cache.
Please remove them from the GAC to fix the issue
