### ISSUE TITLE
Shared metadata cache

### ISSUE THREAD

**Issue by MarkMpn** [MscrmTools/MscrmTools.Xrm.Connection#135]
Most of the XrmToolBox tools I use regularly need to request the metadata, and this is often one of the slowest operations. Each tool tries to cache this with varying levels of success.

If the ConnectionDetails class included a copy of the metadata, each tool could use that instead without any additional performance overhead.

The metadata could be retrieved initially when the connection is first created and saved to a local file. On each subsequent connection it could use the RetrieveMetadataChangesRequest to keep the local cache up to date.

It would cause a few seconds extra delay when creating a new connection or the first time you connect to an existing one, but should lead to a better experience in the tools that use it.

**Comment by MscrmTools** [comment]
I do like the idea!

I'm just wondering how to handle that correctly. 

Ok for using RetrieveMetadataChangesRequest but that would just indicate wether new metadata exists or not. We should then retrieve again ALL metadata. I don't know how much time it would take. Certainly not so much for a vanilla dataverse but for dynamics 365 + portals + other addons, I don't know.

We could let the user decide if he wants to cache metadata for the connection. That could be an option with a flag so that developer knows if he can rely on metadata from ConnectionDetail or if he needs to retrieve them himself.

Another idea, let the tool know if new metadata exists so it can ask the user to download updated metadata?

**Comment by MarkMpn** [comment]
So long as it stores the time stamp along with the metadata, it can supply that value in the next RetrieveMetadataChangesRequest and it will only get the new fields etc. that it could merge into its cached view rather than having to re-download everything when one field changes.

**Comment by MscrmTools** [comment]
Curious to see a gist on how to update existing metadata with the result of the RetrieveMetadataChangesRequest

**Comment by MarkMpn** [comment]
Sure, if you’re happy with the general idea I’ll have a go at an initial implementation over the next few days.

**Comment by MscrmTools** [comment]
Sure, the idea is great 😊

**Comment by MarkMpn** [comment]
I've just put an initial version together and it's taking over 100MB to store the cached metadata, so I'm probably going to need to limit the metadata I'm retrieving. If I limit it to commonly used metadata (logical & display names, attribute types etc) would that still be useful?

**Comment by MscrmTools** [comment]
@MarkMpn I just pushed a new version of connection controls in beta release. This can be tested in real condition now

**Comment by MarkMpn** [comment]
Thanks! One thing I haven't been able to figure out is version support - it works on the oldest on-prem version I've got access to (8.0) but I'm not sure when the `RetrieveMetadataChanges` message was introduced.

**Comment by MscrmTools** [comment]
good catch! I guess it was shipped with 7.1 (online only) so I guess, a check control is necessary if < 8

**Comment by MscrmTools** [comment]
Yes it was 7.1. So I added a check so that `OrganizationMajorVersion` must be >= 8

**Comment by MarkMpn** [comment]
Awesome, I'll give the new build a go against some of my tools over the next few days!

**Comment by MscrmTools** [comment]
It's kind of weird to wait for the metadata to be cached... I connected to two different envs and each time, I was wondering why it was taken so long to connect :) I just hope users won't complain to much
