### ISSUE TITLE
Add existing connection file shows "N/A" in the list of connections

### ISSUE THREAD

**Issue by imranakram** [MscrmTools/MscrmTools.Xrm.Connection#138]
Noticed this bug when I added an existing connections file to XrmToolBox. It shows "N/A" in the list of files in the dialog.
![image](https://user-images.githubusercontent.com/13014005/116402795-1d176800-a82d-11eb-8377-e4b4716b1a9a.png)

And it shows empty string in the flyout menu
![image](https://user-images.githubusercontent.com/13014005/116403003-58b23200-a82d-11eb-8590-bda533ac29aa.png)

---
- Connection Controls Version: 1.2021.2.40
- XrmToolBox Version: 1.2021.4.47

**Comment by MscrmTools** [comment]
Thank you @imranakram 
I must admit it's a long time existing bug... 
As a workaround, you can rename the connection once added. But I have to find a way to avoid this

**Comment by MscrmTools** [comment]
So it seems to be a bug with connection files created long time ago. 
Anyway, I have a fix for this
