### ISSUE TITLE
White font color in connection dialog

### ISSUE THREAD

**Issue by con-ssc** [MscrmTools/MscrmTools.Xrm.Connection#14]
On Windows Server 2008 R2 when you try to make a new connection you have white font on a white background so you cannot see what you are typing. To double check, you can select all and then you can see what you have typed.

**Comment by MscrmTools** [comment]
screenshot, please?

**Comment by con-ssc** [comment]
![image](https://cloud.githubusercontent.com/assets/8189808/20703822/7c8323e4-b61d-11e6-8fba-a134b23e7b2c.png)
![image](https://cloud.githubusercontent.com/assets/8189808/20703840/8c726aa8-b61d-11e6-8e19-65f5df06d734.png)

**Comment by MscrmTools** [comment]
ok, will see what font color is used and if I can improve this
