### ISSUE TITLE
Upgrade 2021.5.47 to latest version unable to connect using saved connections

### ISSUE THREAD

**Issue by thenerdynerd** [MscrmTools/MscrmTools.Xrm.Connection#141]
Hi all - getting an issue today after upgrading to latest version using my stored connections.

Error received:
Invalid URI: The URL is empty

If I downgrade my saved connections are working as expected.

**Comment by MscrmTools** [comment]
Hi,
This is an issue I faced myself but cannot tell exactly what is the root cause for now. 
All this is because of regional discovery service being shut down by Microsoft. Can you recreate the faulty connection? 
For me some connections work as is, some other need to be recreated

**Comment by thenerdynerd** [comment]
Yes that's right - recreation of all 4 connections that I had appears to have fixed the issue at hand.

Thanks for that. Good luck in trying to find the issue, but I think this is a good enough resolution. Recreating connections appeared to be enough.
