### ISSUE TITLE
Invalid URI: The URI is empty - All saved connections are broken and must be re-created

### ISSUE THREAD

**Issue by aovar** [MscrmTools/MscrmTools.Xrm.Connection#144]
**None** of the saved connections work since upgrading to 1.2021.6.51
Re-creating **the exact same** connection with **the same** parameters and details work as expected.

Attempting to connect **any** of the "old" saved connections shows this:
![image](https://user-images.githubusercontent.com/35955914/124579644-9ba50d00-de4f-11eb-9e5c-7880969c3ba8.png)

**Comment by MscrmTools** [comment]
Known issue. As there is a workaround, there is no rush to fix those things

**Comment by aovar** [comment]
Workaround sounds good, how does it work ?

**Comment by MscrmTools** [comment]
well, recreating the connection is a workaround...

As I'm trying to be a nice guy, I just release a beta version of connection controls that should fix the issue. You can try it out if you want
