### ISSUE TITLE
add search by name, server or user

### ISSUE THREAD

**Issue by GuidoPreite** [MscrmTools/MscrmTools.Xrm.Connection#149]
Would be useful to have a textbox (maybe on the top left corner) where a user can write something and after hit enter the connection list returns only the connections where the term is included inside the name, server of user.

Scenario is that several connections are stored and filtering can be useful to don't scroll down the whole list everytime.

**Comment by MscrmTools** [comment]
Hi @GuidoPreite. Thank you for the suggestion.
I'm wondering if the search should happens on all connection files or just the current selected one? 
If only the selected one, should be easy to implement. otherwise, that might be harder (but certainly not impossible)

**Comment by GuidoPreite** [comment]
current selected one is perfect

**Comment by MscrmTools** [comment]
got it!

**Comment by rappen** [comment]
You use connecting files not enough if you need to scroll! 😅
https://youtu.be/mC5FR_LaY4w
