### ISSUE TITLE
Cant create connection

### ISSUE THREAD

**Issue by Mattw112** [MscrmTools/MscrmTools.Xrm.Connection#154]
So I'm a long time user of XRM.  I have numerous connections that work fine.

Today I am trying to connect to a new environment and it keeps failing.  I'm not seeing what the issue is int he log file:

Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	3/4/2022 8:43:20 AM  Initialize CRM connection Started - AuthType: OAuth
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	3/4/2022 8:43:20 AM  Using User Specified Server 
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	3/4/2022 8:43:20 AM  Trying Global Discovery Server (https://globaldisco.crm.dynamics.com/api/discovery/v2.0/Instances) and filtering to region NorthAmerica
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	3/4/2022 8:43:20 AM  Trying Global Discovery Server, (Global Discovery) URI is = https://globaldisco.crm.dynamics.com/api/discovery/v2.0/Instances
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	3/4/2022 8:43:20 AM  DiscoverOrganizations - Called using user of MFA Auth for : https://globaldisco.crm.dynamics.com/api/discovery/v2.0/Instances
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	3/4/2022 8:43:20 AM  DiscoverGlobalOrganizations - Initializing Discovery Server Object with https://globaldisco.crm.dynamics.com/api/discovery/v2.0/Instances
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	3/4/2022 8:43:20 AM  AuthenticateService - found authority with name https://login.microsoftonline.com/common/
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	3/4/2022 8:43:20 AM  AuthenticateService - found resource with name https://globaldisco.crm.dynamics.com/
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	3/4/2022 8:43:20 AM  ObtainAccessToken - CRED
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	3/4/2022 8:43:21 AM  QueryGlobalDiscovery - Initializing Discovery Server Uri with https://globaldisco.crm.dynamics.com/api/discovery/v2.0/Instances
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	3/4/2022 8:43:21 AM  Begin Sending request to /api/discovery/v2.0/Instances : RequestID=c3989fbd-85b0-493a-a81a-24e2a4d4b8e2
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	3/4/2022 8:43:21 AM  Response for request to WebAPI /api/discovery/v2.0/Instances : StatusCode=OK : RequestID=c3989fbd-85b0-493a-a81a-24e2a4d4b8e2 : Duration=00:00:00.6658686
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	3/4/2022 8:43:21 AM  QueryGlobalDiscovery - Discovery Server Get Orgs Call Complete - Elapsed:00:00:00.6681332
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	3/4/2022 8:43:21 AM  Found 39 Org(s)
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Information	8	3/4/2022 8:43:21 AM  Looking for Organization = advservices in the results from CRM's Discovery server list.
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	3/4/2022 8:43:21 AM  Unable to Login to Dynamics CRM
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	3/4/2022 8:43:21 AM  Unable to Login to Dynamics CRM
Source	: Not Provided
Method	: Not Provided
Date	: 3/4/2022
Time	: 8:43:21 AM
Error	: Unable to Login to Dynamics CRM
Stack Trace	: Not Provided

Any ideas?

I have tried several methods to create the connection.  I dont really want to create an AD App though.

Thanks,
Terry

**Comment by MscrmTools** [comment]
no idea...

Did you try to use development appid?

**Comment by Mattw112** [comment]
You mean creating Azure AD application? Or something else?  I've tried pretty much every method besides creating an azure app.  All my other connections to my environments work fine, using the connection wizard.  This is in the same tenant, so not sure why I would need to.

**Comment by Mattw112** [comment]
Any other ideas?  I already have several environments working with XRM.. just this one.. anything potentially int he environment I need to set or change?

**Comment by MscrmTools** [comment]
Connection Wizard don't or won't work anymore with Dynamics 365 Online. It uses WS_TRUST authentication mechanism which is deprecated by Microsoft. 
So older environment might still work but new don't.
You don't have to create an Azure AD Application, just use development settings (it's an universal Azure AD app provided by Microsoft that can be used by any application) provided by connection controls.
