### ISSUE TITLE
Browser / Profile - missing a profile

### ISSUE THREAD

**Issue by rappen** [MscrmTools/MscrmTools.Xrm.Connection#156]
In Chrome, I have "CRM", "CRM-Adm" and "Jonas".
![image](https://user-images.githubusercontent.com/2572253/161511441-5f293194-1d8a-4563-85ae-a6adf0086c9c.png)

Trying to select "Jonas", but it's not there:
![image](https://user-images.githubusercontent.com/2572253/161511646-406aa911-dd6c-49f4-b15a-4b5b8953cac0.png)

No idea why...

**Comment by MscrmTools** [comment]
I'm parsing folders that start with "Profile " in Chrome appData folder. 
It seems that some profile have their own names... Can you check?

**Comment by rappen** [comment]
Not sure... :-/
Do you have a path or so where I should look?

I think my "Jonas" profile was the default profile, and renamed to my name.
Might be found in some default folder...

**Comment by MscrmTools** [comment]
%AppData%\Local\Google\Chrome\User Data

![image](https://user-images.githubusercontent.com/10774317/161557076-52280cbd-b96b-4c66-8079-26a57643a2f7.png)

**Comment by rappen** [comment]
Right - it seems like folder "Default" has same content as "Profile x" folders... So the Default should be added, right?

![image](https://user-images.githubusercontent.com/2572253/161560630-8521e49a-9684-411d-93af-515cd9fdf763.png)
![image](https://user-images.githubusercontent.com/2572253/161560664-5f6e9dee-08f4-4a13-a185-599825553b7d.png)

**Comment by MscrmTools** [comment]
Can you test with beta2 version that should arrives soon?

**Comment by rappen** [comment]
I answer "No" once earlier - how can I update it now...? 🤔
Have to wait until tomorrow?

**Comment by MscrmTools** [comment]
I guess so or update XrmToolBox settings file to change the date of check

**Comment by rappen** [comment]
Deleted settings etc, but nothing, so I had to manually download from nuget - and now it works!

![image](https://user-images.githubusercontent.com/2572253/161716826-33416b9d-7b97-478b-9670-5c129616b8e6.png)

**Comment by MscrmTools** [comment]
Good!
