### ISSUE TITLE
Error while trying to connect to an Org

### ISSUE THREAD

**Issue by con-ssc** [MscrmTools/MscrmTools.Xrm.Connection#19]
Getting an error when trying to connect to an org.
![image](https://cloud.githubusercontent.com/assets/8189808/21850760/645ea64c-d80c-11e6-96d2-2aba6c429843.png)

**Comment by MscrmTools** [comment]
Please update your XrmToolBox to latest version. The plugin is using a method only available in latest version

**Comment by con-ssc** [comment]
Okay, then the auto updater notification does not work.

**Comment by MscrmTools** [comment]
I know, October version is bugged for update notifications
