### ISSUE TITLE
Entering new Connection doesn't generate an id

### ISSUE THREAD

**Issue by con-ssc** [MscrmTools/MscrmTools.Xrm.Connection#20]
After entering an new connection I was unable to start XrmToolbox. I also checked all the DLLs 
![image](https://cloud.githubusercontent.com/assets/8189808/21980602/32a7490c-dbe4-11e6-8950-c5f9345dd99f.png)
Then I checked the mscrmtools2011.config and the connection had no guid in the connectionid.

**Comment by con-ssc** [comment]
Anwendung: XrmToolBox.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.Exception
   bei McTools.Xrm.Connection.ConnectionManager.LoadConnectionsList()
   bei McTools.Xrm.Connection.ConnectionManager.fsw_Changed(System.Object, System.IO.FileSystemEventArgs)
   bei System.IO.FileSystemWatcher.OnChanged(System.IO.FileSystemEventArgs)
   bei System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32, UInt32, System.Threading.NativeOverlapped*)
   bei System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)

**Comment by con-ssc** [comment]
Name der fehlerhaften Anwendung: XrmToolBox.exe, Version: 1.2016.11.4, Zeitstempel: 0x583c4469
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.14393.479, Zeitstempel: 0x582588e6
Ausnahmecode: 0xe0434352
Fehleroffset: 0x0000000000017788
ID des fehlerhaften Prozesses: 0x2795c
Startzeit der fehlerhaften Anwendung: 0x01d2723c36211aba
Pfad der fehlerhaften Anwendung: C:\Users\stefan.schneider\Desktop\XrmToolBox\XrmToolBox.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\System32\KERNELBASE.dll
Berichtskennung: 293e1e69-0fbd-4f14-9141-a93cf79b57b8
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:

**Comment by MscrmTools** [comment]
Hi,
I can create connection and it always has an ID...
That is strange...

**Comment by con-ssc** [comment]
Well, usually I can do that too, but sometimes I run into this error

**Comment by MscrmTools** [comment]
Ok, I will review all calls to Connection constructors to search for a way to create one without having an ID

**Comment by MscrmTools** [comment]
I guess I found the only way to get this error... If you create a connection and during the process you click on the button "Reset", then the Id is wiped out the object

**Comment by MscrmTools** [comment]
it seems there is no other way to get a connection without ID...

or, give me an exact scenario that produces this connection without ID and I will find the cause

**Comment by con-ssc** [comment]
Happened again today. I entered the connection stuff, after I entered the Name of the connection without any special characters or something, the toolbox crashed and I had again a connection without a connectionid.

**Comment by MscrmTools** [comment]
any specific character in the password that might cause this problem?

can you just give me the password (nothing else), so that I can test it on my dev env?

**Comment by con-ssc** [comment]
no special character in connection name, domain, username nor password

**Comment by MscrmTools** [comment]
there has to be something that cannot be handled by the serialization/deserialization scenario...

Is XrmToolBox located in a network share? or some system folder without all permissions?

**Comment by con-ssc** [comment]
no, it is on the desktop.

**Comment by MscrmTools** [comment]
if you try to recreate the exact same connection, does it fail again?

**Comment by rappen** [comment]
FYI - I have seen this issue too, on rare occasions...
Never able to repro in a structured way though.

**Comment by con-ssc** [comment]
Just entered the same information and this time it worked.

**Comment by MscrmTools** [comment]
so it looks like an environment issue. I know it should be handled by the code but as I don't know where it fails, it is hard to handle
