### ISSUE TITLE
Create new connection file fails

### ISSUE THREAD

**Issue by rappen** [MscrmTools/MscrmTools.Xrm.Connection#21]
![image](https://cloud.githubusercontent.com/assets/2572253/22038486/a507d580-dcfb-11e6-8381-a2589c8a4fa3.png)

![image](https://cloud.githubusercontent.com/assets/2572253/22038421/6956ed50-dcfb-11e6-8fce-a15f1435e950.png)

![image](https://cloud.githubusercontent.com/assets/2572253/22038428/6f8c8eaa-dcfb-11e6-8e27-5cdf1413cb3e.png)

Same result if I try it this way:
![image](https://cloud.githubusercontent.com/assets/2572253/22038619/38d96ed6-dcfc-11e6-8504-f1e64d5ad8af.png)

**Comment by rappen** [comment]
If I help a bit by manually creating the Customers.xml file first, I am warned that the file exists, but it is possible to add the file and all connections are moved to the new file (and REmoved from the existing file!)

The Connection file name (not actual file name, but the name property in the xml) is not *Customers*, but *Default*.

**Comment by MscrmTools** [comment]
Found the issue! thanks for reporting

**Comment by rappen** [comment]
Great!

Did this fix also handle the problem that the name entered for the new file is used?

**Comment by MscrmTools** [comment]
yes, as the file was not created, the name was not used at all. It does use the name provided now
