### ISSUE TITLE
Unable to connect to United Kingdom online environment

### ISSUE THREAD

**Issue by DavidNarbona** [MscrmTools/MscrmTools.Xrm.Connection#38]
Hi,

  When we try to connect to Dynamics 365 online environment in a UK tenant we obtain the following error:
  "Metadata contains a reference that cannot be resolved: 
   'https://disco.crm11.dynamics.com/XRMServices/2011/Discovery.svc?wsdl&sdkversion=8.2'".

  Any ideas?

Many thanks & Regards,
David Narbona

**Comment by MscrmTools** [comment]
Yes, use latest version and you should be good

**Comment by DavidNarbona** [comment]
Hi,

  We have v1.2017.7.18. This is the latest version, right?

Thanks & Regards,
David Narbona

**Comment by MscrmTools** [comment]
Yes, so it is "just" a network issue. Does your company use a proxy?

**Comment by DavidNarbona** [comment]
Yes, we have. Must we add any exception?
Many thanks!

**Comment by MscrmTools** [comment]
In XrmToolBox settings, there is a proxy tab. Can you try to fill information there?

**Comment by DavidNarbona** [comment]
It works! 👍 :) Many thanks for your time.
