### ISSUE TITLE
Trying to connect to a

### ISSUE THREAD

**Issue by ds1970** [MscrmTools/MscrmTools.Xrm.Connection#39]
Hi,
We have a online CRM instance with text message authentication.Trying to connect to an online instance, using the connection string, however, I  am not having much luck.
<add name="MyCRMServer" connectionString="AuthType=Office365;Username=XXX.com; Password=XXX;Url= https://XXX.crm4.dynamics.com"/>
![tool](https://user-images.githubusercontent.com/31981135/31718144-1328e014-b40f-11e7-83f0-cb4fe7ce21fe.gif)
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	18-10-2017 10:55:57  Unable to Login to Dynamics CRM
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	18-10-2017 11:01:12  
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	18-10-2017 14:11:13  Unable to Login to Dynamics CRM
**Connection String** <add name="XXX" connectionString="AuthType=Office365;Username=XXX.com; Password=XXX;Url= https://XXX.crm4.dynamics.com"/>

**Comment by MscrmTools** [comment]
can you share your connection string (without password of course)?

**Comment by ds1970** [comment]
<add name="XXX" connectionString="AuthType=Office365;Username=XXX.com; Password=XXX;Url= https://XXX.crm4.dynamics.com"/>

**Comment by OlivierDupuisMSDYN** [comment]
Hi, 
I've got the same problem. 

![2018-01-05_10h16_27](https://user-images.githubusercontent.com/35133945/34602844-b37aea0a-f201-11e7-82fc-e8d7b6bfe26f.png)

Do you have an idea to resolve this problem? I'm on crm4 too on v9 CRM version. 

Best regards 

Olivier

**Comment by MscrmTools** [comment]
Can you confirm you are trying to connect with Multi factor authentication? If so, you need a connection string with Oauth authentication type

**Comment by OlivierDupuisMSDYN** [comment]
Thank you for your answer. 

Multi factor authentication? 

I try to add a new connection with these credentials
URL : https://efrontechdemo14.crm4.dynamics.com
login : xxx@xxxx.onmicrosoft.com
password: xxxxx 

thank

**Comment by MscrmTools** [comment]
This issue was originaly created by a user who was connecting to its organization using SMS authentication. Is that your situation? if not, you would better create a new issue instead of using this one.

**Comment by OlivierDupuisMSDYN** [comment]
Ok i'm on demo instance without SMS authentification
I'll create a new issue
