### ISSUE TITLE
Connection Problems With Siteminder Protected Dynamics 365

### ISSUE THREAD

**Issue by drfunn** [MscrmTools/MscrmTools.Xrm.Connection#40]
Does the XRMToolbox support connecting to Siteminder protected instances of Dynamics 365?

**Comment by MscrmTools** [comment]
I don't even know what siteminder is...

**Comment by drfunn** [comment]
CA Siteminder is a policy based authentication/single sign on tool. Upon accessing a protected site, it checks for an encrypted cookie that is present after authentication. If it does not exit, the user hasn't been authenticated and they get forwarded off to a central Siteminder sign in page. After providing valid credentials they are redirected back to the Dynamics application at which time they can begin using the app.

**Comment by MscrmTools** [comment]
Ok it seems to be too much specific to be handled by this program
