### ISSUE TITLE
4.6.1 framework compatibility

### ISSUE THREAD

**Issue by angelatechair** [MscrmTools/MscrmTools.Xrm.Connection#42]
When attempting to use the XrmToolbox Plugin Project Template I receive errors regarding the framework compatibility. 

Install-Package : Could not install package 'MscrmTools.Xrm.Connection 1.2017.10.15'. You are trying to install this package into a project that targets 
'.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact 
the package author.
At line:1 char:1
+ Install-Package MscrmTools.Xrm.Connection -Version 1.2017.10.15

**Comment by MscrmTools** [comment]
What if you try a project that targets 4.6.2?

**Comment by glosrob** [comment]
Same error targeting 4.6.2 for me as well.

**Comment by angelatechair** [comment]
Yes, I tried multiple targets. Was not successful. Attempting to use the XrmToolBox plugin development template extension for VS 2017. However, I get errors on this dependency. Tried changing to a lower target, but then other dependencies error'd and down the rabbit hole etc etc. This is the first error thrown out of the box when trying to build the xrmtoolbox template.

**Comment by MscrmTools** [comment]
Does it still happen with latest version of the template?
