### ISSUE TITLE
Connecting with Two Factor Authentication - supported?

### ISSUE THREAD

**Issue by DevMunster** [MscrmTools/MscrmTools.Xrm.Connection#43]
Since our client turned on Two Factor Authentication, XRMToolbox won't connect to Dynamics 365 online.
When I use Microsoft's DataMigrationUtility, I had to use the most recent version, and then it sends me SMS authentication etc and works fine.

Is connecting XRMToolbox with Two Factor Authentication Supported?
If it is - how?
I've tried - and failed so far - with a connection string, but, TBH, struggle to understand how they work.

Chris

[XrmToolBox_Connection-2018-01-17.log](https://github.com/MscrmTools/MscrmTools.Xrm.Connection/files/1638573/XrmToolBox_Connection-2018-01-17.log)

**Comment by MscrmTools** [comment]
Hi, it's not supported through connection wizard yet (I'm working on it) but it should work with a connection string (see an example below):

AuthType=OAuth;Username=your_office365_address; Password=the_password;Url=https://organization.crm.dynamics.com;AppId={the id of an app you created in Azure AD that has authorization against CRM Online} ;RedirectUri=http://whatever.com;TokenCacheStorePath=c:\Temp\OauthCache.bin;LoginPrompt=Auto"/>

**Comment by paulobriennz** [comment]
See my solution in here - https://github.com/MscrmTools/MscrmTools.Xrm.Connection/issues/46  

I am currently connected to XrmToolbox using this method.

**Comment by kylebuggie** [comment]
How do you setup the APP ID in Azure?  I found a couple guides online, but they have different steps.
