### ISSUE TITLE
Org URL redirecting to other org.

### ISSUE THREAD

**Issue by migsbeja** [MscrmTools/MscrmTools.Xrm.Connection#44]
Hello,
I have a customer that had an instance with the url https://ABCdev.crm4.dynamics.com after a while he created another one https://ABCdev2.crm4.dynamics.com, because there was some components installed in ABCdev that he didn't wanted and it wasn't possible to remove. So they migrated the components to ABCdev2.
After that procedure was complete, they decided to change the URL's of the orgs.
ABCdev was changed to ABCdevold and ABCdev2 was changed to ABCdev
What happens now is when connecting to the XrmToolBox when the authentications is done we check the connection, the OrganizationDataServiceUrl and the WebApplicationUrl change from ABCdev to ABCdevold and when we look to the entities present, we see that we are connected to the wrong instance.

Is there a way to fix this?

**Comment by migsbeja** [comment]
Is the authentication looking to the Org UniqueName?

**Comment by MscrmTools** [comment]
Here is the [line of code](https://github.com/MscrmTools/MscrmTools.Xrm.Connection/blob/master/McTools.Xrm.Connection/ConnectionDetail.cs#L396) that performs the connection. If something is wrong, it is on Microsoft code.

The Microsoft method retrieves Org unique name from url

I think I cannot do anything for you

**Comment by migsbeja** [comment]
Ok, then it seems that since you are retrieving the Org Unique Name from the Utilities.GetOrgnameAndOnlineRegionFromServiceUri, you are connecting to that specific org (unique name), right?
Then if a customer has:
Org1 unique name: ABCdev -> https://ABCdev.crm4.dynamics.com
Org2 unique name: Org123456 -> https://ABCdev2.crm4.dynamics.com

Then change the URL's of the orgs to:
Org1 unique name: ABCdev -> https://ABCdevold.crm4.dynamics.com
Org2 unique name: Org123456 -> https://ABCdev.crm4.dynamics.com

When connecting to the Org2, we are going to connect to the Org1 in reality because of the code that goes to the Org Unique Name, right?
Wasn't safer to use the just the URL for authentication?

**Comment by MscrmTools** [comment]
It's not about being safer or not. I'm using the code provided by Microsoft to connect to an organization. This is the way to do it. 

I'm quite sure the problem you are facing is because of using the same name as unique org name for Org1 and "url name" for Org2.

You can try to connect using a connection string, this will take the full url as the connection info but maybe Microsoft code does the same thing. After all, code I showed you uses the full url and it seems it does not connect to the appropriate organization.

**Comment by migsbeja** [comment]
I've tried to test it with the code that you are using, in the previous post, and the out of orgName is the same name that is in the URL.

**Comment by MscrmTools** [comment]
So that confirms having two orgs with a shared name for unique name and url name is not handled by MS correctly.

**Comment by migsbeja** [comment]
Well, I've been Debugging the code of MscrmTools.Xrm.Connection and when it is retrieveing the connection here
var tasks = new List<Task<CrmServiceClient>>
                {
                    Task<CrmServiceClient>.Factory.StartNew(() => ConnectOnline(UseOsdp, true)),
                    Task<CrmServiceClient>.Factory.StartNew(() => ConnectOnline(UseOsdp, false))
                };

                tasks[0].Wait();
                tasks[1].Wait();
                
                crmSvc = tasks.FirstOrDefault(t => t.Result.IsReady)?.Result; <---Won't get anything will go to if
                if (crmSvc == null)
                {
                    var uniqueName = ResolveCrmOnlineUniqueOrg();

                    crmSvc = ConnectOnline(UseOsdp, true, uniqueName);

                    if (crmSvc == null)
                    {
                        // None of the attempts above were successful, so get a failed one to be able to display correct error message
                        crmSvc = tasks.FirstOrDefault(t => t.Result != null).Result;
                    }
                }
It is returning that the service connection .IsReady = false then it goes to the if and will go to ResolveCrmOnlineUniqueOrg and when it gets the information from there is getting the other Org.

**Comment by migsbeja** [comment]
I think I figured out at least for this specific problem.
When the code is doing this new CrmServiceClient(UserName, Microsoft.Xrm.Tooling.Connector.CrmServiceClient.MakeSecureString(password), region, orgName, true, useSsl, isOffice365: isOffice365); in the **ConnectOnline** method, you are passing the orgName the one that is retrieved from the method **Utilities.GetOrgnameAndOnlineRegionFromServiceUri** which basically it just gets the org name from the URL.
if it is https://ABCDev.crm4.dynamics.com return ABCDev
If the orgname that is being passed in the new CrmServiceClient is the org UniqueName then the information retrieved is correct.
What are your thoughs on this?

**Comment by migsbeja** [comment]
Hello @MscrmTools ,

I've talked with some Dev's from the Product Group and they referred to this [article](https://msdn.microsoft.com/en-us/library/dn688177.aspx) which mentions:
“For the <OrgName> parameter, you can specify either the **unique** or **friendly name**.”

The method **Utilities.GetOrgnameAndOnlineRegionFromServiceUri**  returns the OrgName but isn't either the Unique of Friendly Name, it is the organization name in the URL.

For example the url https://ABCdev.crm4.dynamics.com "has" an uniquename of org123456 and friendly name ABC development. If we use one of these 2, it connects correctly, if we use the orgname from the URL it connects to the other instance, because when it looks for the uniquename or friendly name, finds only for another Org.

What you are passing in the OrgName for the CrmServiceClient isn't the uniquename or the friendlyname, that is why the customer is having problems connecting to the instance and when he changes the ABCdev.crm4 to org123456.crm4 connects when because Utilities.GetOrgnameAndOnlineRegionFromServiceUri is extracting the org123456 from url.

**Comment by MscrmTools** [comment]
There is an ongoing discussion with Microsoft CRM team about this problem that should not occurs according to them.
They will review there code, so let's wait for the result.
