### ISSUE TITLE
Connecting with Two Factor Authentication

### ISSUE THREAD

**Issue by edddduuuu** [MscrmTools/MscrmTools.Xrm.Connection#46]
Hi,

Since the update on CRM environment with Two Factor Authentication, connecting using XrmToolBox shows "Authentication Failure".
![image](https://user-images.githubusercontent.com/30424815/36955613-7ba728d2-2064-11e8-9684-c668b6f7bf6e.png)

I tried connecting using Connection String but i think i have incorrect format i got from another [thread](https://github.com/MscrmTools/MscrmTools.Xrm.Connection/issues/43).
AuthType=OAuth;Username=your_office365_address; Password=the_password;Url=https://organization.crm.dynamics.com;AppId={the id of an app you created in Azure AD that has authorization against CRM Online} ;RedirectUri=http://whatever.com;TokenCacheStorePath=c:\Temp\OauthCache.bin;LoginPrompt=Auto

Any update regarding this issue? I appreaciate feedbacks from those who can connect using XrmToolbox. :)

Regards,
Edu

**Comment by edddduuuu** [comment]
I'd like to confirm if the AppId is the OrgId in CRM.
![image](https://user-images.githubusercontent.com/30424815/36955822-c91a3cde-2065-11e8-80e6-cf980b53d3f4.png)

Also, what should be RedirectUri?

**Comment by MscrmTools** [comment]
App id and redirect uri comes from an Azure AD  application you need to create yourself

**Comment by edddduuuu** [comment]
I just need to connect to CRM online using XrmToolbox by redirecting here. 
![image](https://user-images.githubusercontent.com/30424815/36967252-2d5bd0c0-209a-11e8-9492-16b7c8977f1c.png)
How can i do this?

**Comment by paulobriennz** [comment]
Hello, I had very similar issue with MFA with CRM Online using a CRM Connection String method.  I haven't tried this myself against XrmToolbox, but I think this format should work.  
1. Go an create an application in Azure portal - I set the Redirect URI to http://localhost
2. Select Dynamisc CRM Online (Microsoft.CRM)
3. Select Acccess Crm Online as organization users under permissions

Use this format as a connection string:
AuthType=OAuth;Url=https://yourcrm.crm.dynamics.com;AppId=yournewappid;RedirectUri=http://localhost;

**Comment by paulobriennz** [comment]
Now I have a question :) exactly the same situation but with CRM On-Premise (IFD) and ADFS/MFA.
I can't for the life of me figure out the Connection String format to use for On-Prem MFA with ADFS.  I've gone into ADFS and i think i'm meant to 'register' an application, although i'm not sure as i can't find any guide on this.  
I ran this command:
Add-AdfsClient -ClientId 12171175-f604-48a4-a13a-211a82b8ddcd -Name XrmToolbox -RedirectUri http://localhost/

if i do a Get-AdfsClient - i see a result.. 

Does anyone have a definitive guide on how to connect to XrmToolbox (or any application using the CRM Tooling / Connection String) with On-Prem IFD CRM using ADFS/On-Prem MFA?  I've asked on stackoverflow and dynamics crm forums and no response...

**Comment by kljozefvl** [comment]
I'm also having trouble to connect with MFA. APP created and MFA works throuhg control on phone. However after that it says it needs a request using client_secret
but none of the given examples mentions this. Were are we going wrong?

**Comment by mppowe** [comment]
@paulobriennz  Did you ever figure out how to make this work with on-prem IFD and on-prem ADFS/MFA?
