### ISSUE TITLE
Early Bound Generator will not connect to D365 V9.0.1.459

### ISSUE THREAD

**Issue by clintolin** [MscrmTools/MscrmTools.Xrm.Connection#47]
I am using XrmToolBox v1.2018.1.20. 

My dev environment just updated to D365 V9.0.1.459 and when trying to generate classes with Early Bound Generator, it connects, displays organizations, I select one but it just continuously prompts for login. Using other tools such as FetchXML Builder connects and executes just fine. 

![capture](https://user-images.githubusercontent.com/7000083/37114328-f0a4ece6-223f-11e8-9d6f-c1de4f97fbf0.PNG)

The log shows "Attempting to login using interactive mode" even though I have logged in to the Dev environment using my saved connection settings.  

Then it shows:

![capture1](https://user-images.githubusercontent.com/7000083/37114343-f8f3f7c0-223f-11e8-92fd-629055a36ad6.PNG)

Then it just repeats until finally I push Cancel and it shows "User aborted Login" (of course). 

I can connect to Test, D365 V8.2.2.339 and it works just fine.

**Comment by MscrmTools** [comment]
This is an issue to open in early bound generator repository as it does not use my code.
