### ISSUE TITLE
Unable to connect to Dynamics 365

### ISSUE THREAD

**Issue by marcogrimaldi** [MscrmTools/MscrmTools.Xrm.Connection#49]
Tried different ways:
1) Connection wizard -> Entered URL (https://ORGNAME.crm.dynamics.com) -> Username and password
RESULT: 
"Unable to login to Dynamics CRM. 
If the unique name of you organization is different from the name used in the url provided..."

2) Connection wizard -> Entered URL (https://ORG_UNIQUE_ID.crm.dynamics.com) -> Username and password
RESULT: 
"Unable to find the organization based on its url name. 
If the unique name of you organization is different from the name used in the url provided..."

3) Connection wizard -> Provide ConnectionString -> tried with`
<add name="OnlineQA" connectionString="AuthType=Office365;Username=xxx@yyy.com; Password=zzzzzzzz;Url=https://orgXXXXXX.crm.dynamics.com"/>`
RESULT: 
"Organization Name cannot be null or empty.
Parameter Name: Organization Name."

Thanks,
Marco

**Comment by shytikov** [comment]
Is still valid for most recent version?
