### ISSUE TITLE
Value cannot be null - Parameter name: s

### ISSUE THREAD

**Issue by FrederickLecavalier** [MscrmTools/MscrmTools.Xrm.Connection#54]
Having a strange issue with the latest version 

I create / test / save a new connection without any error.

When I try to use it, I get the following message 

![image](https://user-images.githubusercontent.com/41200862/42706288-3d623d04-86a4-11e8-9aaa-3ce642e04153.png)

Am I missing something ?

**Comment by MscrmTools** [comment]
Is it online if onprem?
Can you check the connection in the connections file to check if some value seems empty?

**Comment by shytikov** [comment]
Seems to be the same as #56

**Comment by shytikov** [comment]
Sorry wrong commits :) Already removed.

**Comment by shytikov** [comment]
This bug seems to be related to `Use your current credentials` settings. 

When you check it `XTB` still tries to decrypt your password from configuration file. But there is no password, because we supposed to guess your credentials.

So `null` string tries to be decrypted, and you get the error which blocks the rest.

**Comment by shytikov** [comment]
Trying to understand how to fix that, I'm not familiar that much with the internal mechanics of this module, maybe @MscrmTools can step it (meanwhile I will keep trying).

**Comment by shytikov** [comment]
I have checked in help to SDK functions `AD` credentials supported for `AD` and `IFD` connections. 

So, for `Online` connections this checkbox should be disabled.

**Comment by shytikov** [comment]
I didn't disabled the checkbox, since it requires more invasive intrusion, but added helper text as caption to prevent (kind of) incorrect usage.
