### ISSUE TITLE
Unable to login to Dynamics CRM

### ISSUE THREAD

**Issue by zenecamickeyd** [MscrmTools/MscrmTools.Xrm.Connection#56]
I recently installed the latest version (1.2018.7.26) and had to uninstall the following 2 plugins before XRMToolBox would load:

1. Colso.DashboardTransferTool
2. Colso.Xrm.ChartTransferTool

Now however I cannot connect to either our Production or Sandbox D365O instances.  I simply get the message "Unable to login to Dynamics CRM".  I have attached what I believe is the log file containing the error(s).

[XrmToolBox_Connection-2018-07-18.log](https://github.com/MscrmTools/MscrmTools.Xrm.Connection/files/2206138/XrmToolBox_Connection-2018-07-18.log)

**Comment by MscrmTools** [comment]
Hi,
I'm using latest version with D365 Online (v8.2 and v9) and OnPremise (v8.2) instances without any trouble so the problem should not be related to XrmToolBox.

There is many root cause for the error message in the logs, like wrong password, unsynced computer time between your computer and the server, proxy that causes some kind of troubles...

**Comment by zenecamickeyd** [comment]
I've just tried to create a new connection using the Organization URL https://<organization unique name>.crm4.dynamics.com with the following settings:

- **Use your current credentials** = checked
- **Use Multi Factor Authentication** = unchecked
- **Service timeout** = 00:02:00

When I click next I get the message _"Value cannot be null.  Parameter name 's'"._

We use SSO and I can successfully access both of our D365O instances via a web browser and my SSO credentials.

**Comment by MscrmTools** [comment]
Can you try not to use your current credentials but type your credentials again?

**Comment by zenecamickeyd** [comment]
I've just done that and now get the message _"Unable to Login to Dynamics CRM"_.  I tried this with the option **Save password as encrypted string in connections file** both ticked and unticked, and I get the same error message.

**Comment by MscrmTools** [comment]
what kind of username do you use?

**Comment by zenecamickeyd** [comment]
O365 email address.

**Comment by MscrmTools** [comment]
So it should be good...

Latest version did not change the way connecting to D365 Online is made so I clearly don't understand why it does not work...

I guess I know the answer but is there any chance your provide me credentials privately so I can try myself to connect?

**Comment by zenecamickeyd** [comment]
No, sorry I can't do that.

**Comment by MscrmTools** [comment]
ok, so I cannot do anything for you, I am sorry. If there was really a global issue when connecting to CRM Online, then I guess I would have received a lot of issues here and you are the first and only one so far

**Comment by zenecamickeyd** [comment]
Do you have any suggestions?  We are in the middle of implementing a load of view changes, which the View Designer plugin is invaluable for.

Like I said I've been using the tool a lot recently and have had any issues connecting until today, and I've not changed any of the connection details or my password.

**Comment by MscrmTools** [comment]
The only suggestion I have so far is to download previous version, if the problem really comes from the new version

**Comment by zenecamickeyd** [comment]
Got a link for the previous version?  Do I need to uninstall the current version first?

**Comment by MscrmTools** [comment]
Here is the [link](https://github.com/MscrmTools/XrmToolBox/releases/download/v.1.2018.6.23/XrmToolbox.zip)

You can keep the newest version but to be sure you don't share any settings, before running XrmToolBox, create a shortcut for xrmtoolbox.exe and edit it, add the following argument : /overridepath:.

It tells XrmToolBox to install its files (plugins, settings, etc.) on the same folder where xrmtoolbox.exe is located

**Comment by shytikov** [comment]
Are you connecting via connection string?

I believe this error**S** (there are plenty of them around connection module) are related to connection strings. For some reason (I haven't checked the code yet) when I use connection string `XTB` still tries to go for discovery URL, which is empty. So...

There are some other sporadic things, that I not able to reproduce every time — changes in connection string is not saved, connection is impossible to delete (!!!), sometimes pressing `Back` button on connection dialog crashes whole app...

I will try to add my 2¢ to fixing that, but for me looks like fresh version is not usable unless connections from previous one are preserved, and not changed.

**Comment by SrinivasPodili** [comment]
@MSCRMTools: I am also facing the same issue from last couple of months. Can you please check and fix the issue?

**Comment by MscrmTools** [comment]
Can you send log files?

**Comment by SrinivasPodili** [comment]
I am getting this error only when connecting from Internet. Inside on premise/internal same tool is working without any issue.
attached the logs

**Comment by SrinivasPodili** [comment]
Logs
[XrmToolBox_Connection-2019-11-23.log](https://github.com/MscrmTools/MscrmTools.Xrm.Connection/files/3963697/XrmToolBox_Connection-2019-11-23.log)

**Comment by SrinivasPodili** [comment]
@MscrmTools : I have uploaded the logs.
