### ISSUE TITLE
Connecting to Guest tenant with Azure B2B account fails

### ISSUE THREAD

**Issue by brianilland** [MscrmTools/MscrmTools.Xrm.Connection#72]
I have the following set up.

- An Azure account in my own 'home' O365 tenant which has my own D365 instances
- This same account has been added as a guest B2B account (so source = External Azure Active Directory) in another O365 tenant.
- When I connect using XRMToolbox to a guest D365 instance the connection fails.
- When I trace the request using Fiddler4, I can see it is because a call to the Discovery Service is returning the instances from my 'Home' tenant, and not the Guest tenant.

Is this a limitation of the way that XRMToolbox uses the Discovery service, or is this an issue outside of XRMToolbox?

Any questions, happy to clarify.

**Comment by MscrmTools** [comment]
That could be an internal bug since I'm just using the default CrmServiceClient constructors but I might use them wrong in your own configuration.
If you are a developper, any chance you try to construct CrmServiceClient until you find the appropriate way to use it?

**Comment by brianilland** [comment]
Ok, I will have a look into this and see how we go.
