### ISSUE TITLE
unable to compile solution - cannot import .pfx file

### ISSUE THREAD

**Issue by dotcentric-samb** [MscrmTools/MscrmTools.Xrm.Connection#73]
Hi,

I am trying to use this tool to connect to an instance of microsoft dynamics. I have cloned the repository and then opened the solution in visual studio. When i build the solution i get errors from the McTools.Xrm.Connection and McTools.Xrm.Connection.WinForms projects. The error message is:

"Cannot import the following key file: McTools.Xrm.Connection.pfx. The key file may be password protected. To correct this, try to import the certificate again or manually install the certificate to the Strong Name CSP with the following key container name: VS_KEY_A06718AB45658823"

I don't understand what i need to do to resolve this error. Is there a readme file for this program somewhere i might have missed? I can't see any instructions on how to set it up.

Sam

**Comment by MscrmTools** [comment]
Remove the snk file and add yours.
This is to ensure no one deliver my code with my signature
