### ISSUE TITLE
Support for Client ID and Client Secret Connection Method

### ISSUE THREAD

**Issue by fayezm** [MscrmTools/MscrmTools.Xrm.Connection#74]
We have a situation where a government client has a really complicated SSO configuration for D365 (cloud). We've found that the only way we have been able to connect to their instance programatically is via the use of a Client ID and Client Secret. All the other methods throw up different types of errors.

Can this connection method be made available?

**Comment by MscrmTools** [comment]
If you can share the code you are using to successfully connect, then I could try to implement it

**Comment by fayezm** [comment]
I have implemented the AuthOverride hook based on this example: https://gist.github.com/justlikeed/5f605cfac460c4ce039811ce6d19bf6a

and made the following modifications for authenticating. It obviously requires some set up in Azure AD

`AuthenticationParameters ap = AuthenticationParameters.CreateFromResourceUrlAsync(new Uri("https://myorg.crm6.dynamics.com/api/data/")).Result;

String authorityUrl = ap.Authority;
String resourceUrl = ap.Resource;

// Authenticate the registered application with Azure Active Directory.  
AuthenticationContext authContext = new AuthenticationContext(authorityUrl, false);

var clientCred = new ClientCredential("CLIENT ID", "SECRETKEY");

var result =  authContext.AcquireToken(resourceUrl, clientCred);`

**Comment by MscrmTools** [comment]
Supported in latest version
