### ISSUE TITLE
Unable to Login to Dynamics CRM

### ISSUE THREAD

**Issue by allvar** [MscrmTools/MscrmTools.Xrm.Connection#8]
The error is given when trying to connect to an on-prem installed IFD environment. The error in XTB trace file is
Error	: ID3242: The security token could not be authenticated or authorized.

I've tried (almost) every combination of URL (both disco server and app-server), username (both xxx\yyy and xxx@yyy.zzz) etc. but all fails.

Any hints?

I should add that this is a new issue with the latest version of XTB. Previous versions all work fine.

**Comment by MscrmTools** [comment]
I don't have any hint right now... I can just tell you that next release will support connection string so that each and every deployment types will be supported

**Comment by rappen** [comment]
Connection string style has been tested too, unfortunately...

**Comment by MscrmTools** [comment]
What does it mean? that even with a connection string in the pre release version you cannot connect to the org? if so, it means that the bug is on Microsoft side as the connection string is never altered by the program and used as is

**Comment by rappen** [comment]
Probably you are right @MscrmTools. Or it means that the connection string still was not formed in a correct way...
We will continue investigation and also try the ``LoginControlTester``.

**Comment by MscrmTools** [comment]
For the connection string, compared to previous version, it is now mandatory to specify the AuthType parameter. Did you do that?

**Comment by allvar** [comment]
The Login Control Tester works but I cannot get a connection string to work.

**Comment by MscrmTools** [comment]
can you share (without the password, obviously) your connection string?

**Comment by allvar** [comment]
Url=https://<url to discoserver>;Username=xxx@veranet.se;AuthType=IFD;Password=yyy
The above gives "Organization cannot be null or empty" error

Url=https://<url to discoserver>/organization;Username=xxx@veranet.se;AuthType=IFD;Password=yyy
Gives error "Cannot login..."

Url=https://<url to appserver>/organization;Username=xxx@veranet.se;AuthType=IFD;Password=yyy
Gives error "Cannot login..."

**Comment by MscrmTools** [comment]
Can you try not to use an email address for username but only the name or domain\name?

**Comment by allvar** [comment]
Done that - been there :-)
Sorry, same result.

**Comment by MscrmTools** [comment]
And what about adding a Domain parameter which contains the domain part of the login and Username parameter containing only the login name?

**Comment by allvar** [comment]
Done that too...

**Comment by MscrmTools** [comment]
What version of CRM?

**Comment by allvar** [comment]
2013 sp1

Best regards
Allan Varcoe, Cinteros AB
Mobile: +46 70 340 3841

**Comment by MscrmTools** [comment]
I don't have IFD deployment for this version, so I cannot test myself
Did you activate tracing?

**Comment by MscrmTools** [comment]
I think this issue is now to be closed as per our email conversation
I allowed not to fill the domain name when connecting to an ifd deployment
