### ISSUE TITLE
Cannot connect to CRM since using RSA

### ISSUE THREAD

**Issue by CPow123** [MscrmTools/MscrmTools.Xrm.Connection#82]
Hello,

Since our firm has begun using RSA multi-factor authenticating we have been unable to connect to our CRM orgs in the toolbox. Have you worked around this before? Your assistance is greatly appreciated.

**Comment by MscrmTools** [comment]
I never had to work with this kind of MFA. Is it linked to Office 365 or not?

**Comment by CPow123** [comment]
Yes, it's linked to Office 365.

**Comment by MscrmTools** [comment]
Ok so you might try to connect using a connection string built for MFA

**Comment by imranakram** [comment]
@MscrmTools I've made a pull request since we're facing the same scenario at our company
