### ISSUE TITLE
Unable to connect after upgrading to 1.2019.2.30

### ISSUE THREAD

**Issue by bryansonofpatt** [MscrmTools/MscrmTools.Xrm.Connection#87]
[XrmToolBox_Connection-2019-02-28.log](https://github.com/MscrmTools/MscrmTools.Xrm.Connection/files/2916075/XrmToolBox_Connection-2019-02-28.log)

I was running v1.2018.7.28 and upgraded to latest v1.2019.2.30 and now none of my connections can connect.

**Comment by sjhaymore** [comment]
Did you figure anything out? I am having the same issue.
Thanks.

**Comment by vgallardo75** [comment]
No. I have a meeting with our internal IT team today to have a look as well. 

Sent from my iPhone

On Feb 28, 2019, at 11:53 AM, sjhaymore <notifications@github.com> wrote:

Did you figure anything out? I am having the same issue.
Thanks.

**Comment by sjhaymore** [comment]
I just re-installed v1.2018.10.29 and it is now working again. I won't install another upgrade any time soon!

**Comment by MscrmTools** [comment]
Sorry for the trouble, I'm still investigating why connecting to OnPremise organization don't work anymore.
 You can download the previous version here : https://github.com/MscrmTools/XrmToolBox/releases/download/v.1.2018.10.29/XrmToolbox.zip

**Comment by MscrmTools** [comment]
Ok everyone, I got the confirmation from Microsoft there was a bug in one of their version. Let me update to their latest bit and we will be good!
