### ISSUE TITLE
GPL License

### ISSUE THREAD

**Issue by slautebach** [MscrmTools/MscrmTools.Xrm.Connection#92]
I would like to use this library within my dynamics project I am working on.  But notice that the license is just GPL, and not LGPL.  Limiting me from using this in a potential closed source application.  My question is the project open to the idea of dual-licensing this project under both the GPL and LGPL?  That way the community would be able to make use of it within all types of projects.

**Comment by MscrmTools** [comment]
I must admit I’m not an expert of code licensing so used the most common license.
What LGPL would bring more than GPL that helps you?

**Comment by slautebach** [comment]
Under GPL, linking to this project by any other project requires that project to also be licensed under the GPL license.  LGPL https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License license allow other projects that link to it, to fall under their license of their choice.   The license allows projects to maintains the GPL style license but removes the restriction that any project linking to it also fall under GPL.  You can even license a project under multiple license https://en.wikipedia.org/wiki/Multi-licensing

**Comment by slautebach** [comment]
Have you thought about this any further?  Thank you in advance.

**Comment by MscrmTools** [comment]
Sorry for the extra long delay.
This repository is now under LGPL
