### ISSUE TITLE
Method not found: Xrm.Tooling.Connector...MaxConnectionTimeout

### ISSUE THREAD

**Issue by shmcgrath** [MscrmTools/MscrmTools.Xrm.Connection#96]
Hello. After updating to the latest version, deleting the app and all Mscrmtools settings in appdata, and re-extracting the app and running as admin, I’m still unable to connect using the Connection Wizard or the SDK Login. Any help would be appreciated.

Here is a screenshot of the error:
![42FB3F81-D126-4F7C-99DC-995988B91118](https://user-images.githubusercontent.com/877042/65260809-f469b100-dad4-11e9-80bd-90a7fafda2c0.png)

Here are the logs:
See the end of this message for details on invoking
just-in-time (JIT) debugging instead of this dialog box.
 
************** Exception Text **************
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
  at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
  at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
  at McTools.Xrm.Connection.WinForms.CustomControls.ConnectionFailedControl.llOpenConnectionLog_LinkClicked(Object sender, LinkLabelLinkClickedEventArgs e)
  at System.Windows.Forms.LinkLabel.OnLinkClicked(LinkLabelLinkClickedEventArgs e)
  at System.Windows.Forms.LinkLabel.OnMouseUp(MouseEventArgs e)
  at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
  at System.Windows.Forms.Control.WndProc(Message& m)
  at System.Windows.Forms.Label.WndProc(Message& m)
  at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
 
 
************** Loaded Assemblies **************
mscorlib
  Assembly Version: 4.0.0.0
  Win32 Version: 4.8.3928.0 built by: NET48REL1
  CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
XrmToolBox
  Assembly Version: 1.2019.7.34
  Win32 Version: 1.2019.7.34
  CodeBase: file:///C:/XrmToolbox/XrmToolBox.exe
----------------------------------------
System.Core
  Assembly Version: 4.0.0.0
  Win32 Version: 4.8.3928.0 built by: NET48REL1
  CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
  Assembly Version: 4.0.0.0
  Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
  CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
XrmToolBox.Extensibility
  Assembly Version: 1.2019.7.34
  Win32 Version: 1.2019.7.34
  CodeBase: file:///C:/XrmToolbox/XrmToolBox.Extensibility.DLL
----------------------------------------
System.Windows.Forms
  Assembly Version: 4.0.0.0
  Win32 Version: 4.8.3928.0 built by: NET48REL1
  CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
  Assembly Version: 4.0.0.0
  Win32 Version: 4.8.3761.0 built by: NET48REL1
  CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Microsoft.IdentityModel
  Assembly Version: 3.5.0.0
  Win32 Version: 10.0.17134.885
  CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Microsoft.IdentityModel/3.5.0.0__31bf3856ad364e35/Microsoft.IdentityModel.dll
----------------------------------------
System.IO.Compression.FileSystem
  Assembly Version: 4.0.0.0
  Win32 Version: 4.8.3761.0
  CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression.FileSystem/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.FileSystem.dll
----------------------------------------
XrmToolBox.PluginsStore
  Assembly Version: 1.2019.7.34
  Win32 Version: 1.2019.7.34
  CodeBase: file:///C:/XrmToolbox/XrmToolBox.PluginsStore.DLL
----------------------------------------
NuGet.Core
  Assembly Version: 2.14.0.832
  Win32 Version: 2.14.0.832
  CodeBase: file:///C:/XrmToolbox/NuGet.Core.DLL
----------------------------------------
Newtonsoft.Json
  Assembly Version: 12.0.0.0
  Win32 Version: 12.0.2.23222
  CodeBase: file:///C:/XrmToolbox/Newtonsoft.Json.DLL
----------------------------------------
McTools.Xrm.Connection
  Assembly Version: 1.2019.6.25
  Win32 Version: 1.2019.6.25
  CodeBase: file:///C:/XrmToolbox/McTools.Xrm.Connection.DLL
----------------------------------------
McTools.Xrm.Connection.WinForms
  Assembly Version: 1.2019.6.25
  Win32 Version: 1.2019.6.25
  CodeBase: file:///C:/XrmToolbox/McTools.Xrm.Connection.WinForms.DLL
----------------------------------------
Microsoft.Xrm.Sdk
  Assembly Version: 9.0.0.0
  Win32 Version: 9.0.9002.0
  CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.Xrm.Sdk/v4.0_9.0.0.0__31bf3856ad364e35/Microsoft.Xrm.Sdk.dll
----------------------------------------
Microsoft.Xrm.Sdk.Workflow
  Assembly Version: 9.0.0.0
  Win32 Version: 9.0.37.958
  CodeBase: file:///C:/XrmToolbox/Microsoft.Xrm.Sdk.Workflow.DLL
----------------------------------------
Microsoft.Crm.Sdk.Proxy
  Assembly Version: 9.0.0.0
  Win32 Version: 9.0.0.1103
  CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.Crm.Sdk.Proxy/v4.0_9.0.0.0__31bf3856ad364e35/Microsoft.Crm.Sdk.Proxy.dll
----------------------------------------
Microsoft.Xrm.Tooling.Connector
  Assembly Version: 3.0.0.0
  Win32 Version: 3.0.0.949
  CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.Xrm.Tooling.Connector/v4.0_3.0.0.0__31bf3856ad364e35/Microsoft.Xrm.Tooling.Connector.dll
----------------------------------------
Microsoft.Xrm.Tooling.Ui.Styles
  Assembly Version: 3.0.0.0
  Win32 Version: 3.8.0.1000
  CodeBase: file:///C:/XrmToolbox/Microsoft.Xrm.Tooling.Ui.Styles.DLL
----------------------------------------
Microsoft.Xrm.Tooling.CrmConnectControl
  Assembly Version: 3.0.0.0
  Win32 Version: 3.0.0.1000
  CodeBase: file:///C:/XrmToolbox/Microsoft.Xrm.Tooling.CrmConnectControl.DLL
----------------------------------------
Microsoft.IdentityModel.Clients.ActiveDirectory
  Assembly Version: 2.29.0.1078
 Win32 Version: 2.29.40822.1520
  CodeBase: file:///C:/XrmToolbox/Microsoft.IdentityModel.Clients.ActiveDirectory.DLL
----------------------------------------
Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms
  Assembly Version: 2.29.0.1078
  Win32 Version: 2.29.40822.1520
  CodeBase: file:///C:/XrmToolbox/Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms.DLL
----------------------------------------
WeifenLuo.WinFormsUI.Docking
  Assembly Version: 3.0.6.0
  Win32 Version: 3.0.6.0
  CodeBase: file:///C:/XrmToolbox/WeifenLuo.WinFormsUI.Docking.DLL
----------------------------------------
WeifenLuo.WinFormsUI.Docking.ThemeVS2015
  Assembly Version: 3.0.6.0
  Win32 Version: 3.0.6.0
  CodeBase: file:///C:/XrmToolbox/WeifenLuo.WinFormsUI.Docking.ThemeVS2015.DLL
----------------------------------------
System.Configuration
  Assembly Version: 4.0.0.0
  Win32 Version: 4.8.3761.0 built by: NET48REL1
  CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
  Assembly Version: 4.0.0.0
  Win32 Version: 4.8.3761.0 built by: NET48REL1
  CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Runtime.Serialization
  Assembly Version: 4.0.0.0
  Win32 Version: 4.8.3928.0 built by: NET48REL1
  CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
SMDiagnostics
  Assembly Version: 4.0.0.0
  Win32 Version: 4.8.3928.0 built by: NET48REL1
  CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.ServiceModel.Internals
  Assembly Version: 4.0.0.0
  Win32 Version: 4.8.3928.0 built by: NET48REL1
  CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
System.Net.Http
  Assembly Version: 4.0.0.0
  Win32 Version: 4.8.3761.0 built by: NET48REL1
  CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
Microsoft.GeneratedCode
  Assembly Version: 1.0.0.0
  Win32 Version: 4.8.3761.0 built by: NET48REL1
  CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Xml.Linq
  Assembly Version: 4.0.0.0
  Win32 Version: 4.8.3761.0 built by: NET48REL1
  CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
McTools.StopAdvertisement
  Assembly Version: 1.0.0.0
  Win32 Version: 1.0.0.0
  CodeBase: file:///C:/XrmToolbox/McTools.StopAdvertisement.DLL
----------------------------------------
Microsoft.GeneratedCode
  Assembly Version: 1.0.0.0
  Win32 Version: 4.8.3761.0 built by: NET48REL1
  CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.ComponentModel.Composition
  Assembly Version: 4.0.0.0
  Win32 Version: 4.8.3761.0
  CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
DamSim.SolutionTransferTool
  Assembly Version: 1.2018.10.9
  Win32 Version: 1.2018.10.9
  CodeBase: file:///C:/USERS/SMCGRATH/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/DAMSIM.SOLUTIONTRANSFERTOOL.DLL
----------------------------------------
DamSim.ViewTransferTool
  Assembly Version: 1.2018.3.3
  Win32 Version: 1.2018.3.3
  CodeBase: file:///C:/USERS/SMCGRATH/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/DAMSIM.VIEWTRANSFERTOOL.DLL
----------------------------------------
GapConsulting.PowerBIOptionSetAssistant
  Assembly Version: 1.2018.6.3
  Win32 Version: 1.2018.6.3
  CodeBase: file:///C:/USERS/SMCGRATH/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/GAPCONSULTING.POWERBIOPTIONSETASSISTANT.DLL
----------------------------------------
Javista.XrmToolBox.ImportNN
  Assembly Version: 1.2018.3.8
  Win32 Version: 1.2018.3.8
  CodeBase: file:///C:/USERS/SMCGRATH/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/JAVISTA.XRMTOOLBOX.IMPORTNN.DLL
----------------------------------------
MsCrmTools.AccessChecker
  Assembly Version: 1.2018.7.2
  Win32 Version: 1.2018.7.2
  CodeBase: file:///C:/USERS/SMCGRATH/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ACCESSCHECKER.DLL
----------------------------------------
MsCrmTools.AssemblyRecoveryTool
  Assembly Version: 1.2018.3.2
  Win32 Version: 1.2018.3.2
  CodeBase: file:///C:/USERS/SMCGRATH/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ASSEMBLYRECOVERYTOOL.DLL
----------------------------------------
MsCrmTools.AttributeBulkUpdater
  Assembly Version: 1.2019.5.3
  Win32 Version: 1.2019.5.3
  CodeBase: file:///C:/USERS/SMCGRATH/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ATTRIBUTEBULKUPDATER.DLL
----------------------------------------
MscrmTools.AttributeUsageInspector
  Assembly Version: 1.2018.9.11
  Win32 Version: 1.2018.9.11
  CodeBase: file:///C:/USERS/SMCGRATH/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ATTRIBUTEUSAGEINSPECTOR.DLL
----------------------------------------
MsCrmTools.AuditCenter
  Assembly Version: 1.2016.9.1
  Win32 Version: 1.2016.9.1
  CodeBase: file:///C:/USERS/SMCGRATH/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.AUDITCENTER.DLL
----------------------------------------
MsCrmTools.ChartManager
  Assembly Version: 1.2017.3.1
  Win32 Version: 1.2017.3.1
  CodeBase: file:///C:/USERS/SMCGRATH/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.CHARTMANAGER.DLL
----------------------------------------
MscrmTools.CrmTraceReader
  Assembly Version: 1.2018.4.1
  Win32 Version: 1.2018.4.1
  CodeBase: file:///C:/USERS/SMCGRATH/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.CRMTRACEREADER.DLL
----------------------------------------
MsCrmTools.DocumentTemplatesMover
  Assembly Version: 1.2018.4.3
  Win32 Version: 1.2018.4.3
  CodeBase: file:///C:/USERS/SMCGRATH/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.DOCUMENTTEMPLATESMOVER.DLL
----------------------------------------
MsCrmTools.FlsBulkUpdater
  Assembly Version: 1.2016.12.1
  Win32 Version: 1.2016.12.1
  CodeBase: file:///C:/USERS/SMCGRATH/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FLSBULKUPDATER.DLL
----------------------------------------
MsCrmTools.FormRelated
  Assembly Version: 1.2017.12.3
  Win32 Version: 1.2017.12.3
  CodeBase: file:///C:/USERS/SMCGRATH/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.FORMRELATED.DLL
----------------------------------------
MsCrmTools.Iconator
  Assembly Version: 1.2018.7.9
  Win32 Version: 1.2018.7.9
  CodeBase: file:///C:/USERS/SMCGRATH/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.ICONATOR.DLL
----------------------------------------
MscrmTools.ManagedSolutionDeletionTool
  Assembly Version: 1.2016.11.1
  Win32 Version: 1.2016.11.1
  CodeBase: file:///C:/USERS/SMCGRATH/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.MANAGEDSOLUTIONDELETIONTOOL.DLL
----------------------------------------
MsCrmTools.MetadataBrowser
  Assembly Version: 1.2019.6.12
  Win32 Version: 1.2019.6.12
  CodeBase: file:///C:/USERS/SMCGRATH/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.METADATABROWSER.DLL
----------------------------------------
MsCrmTools.MetadataDocumentGenerator
  Assembly Version: 1.2019.5.1
  Win32 Version: 1.2019.5.1
  CodeBase: file:///C:/USERS/SMCGRATH/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.METADATADOCUMENTGENERATOR.DLL
----------------------------------------
MscrmTools.PortalCodeEditor
  Assembly Version: 1.2019.6.10
  Win32 Version: 1.2019.6.10
  CodeBase: file:///C:/USERS/SMCGRATH/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.PORTALCODEEDITOR.DLL
----------------------------------------
MscrmTools.PortalRecordsMover
  Assembly Version: 1.2019.7.7
  Win32 Version: 1.2019.7.7
  CodeBase: file:///C:/USERS/SMCGRATH/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.PORTALRECORDSMOVER.DLL
----------------------------------------
MsCrmTools.SampleTool
  Assembly Version: 1.2018.6.23
  Win32 Version: 1.2018.6.23
  CodeBase: file:///C:/USERS/SMCGRATH/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SAMPLETOOL.DLL
----------------------------------------
MsCrmTools.ScriptsFinder
  Assembly Version: 1.2019.3.11
  Win32 Version: 1.2019.3.11
  CodeBase: file:///C:/USERS/SMCGRATH/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SCRIPTSFINDER.DLL
----------------------------------------
MsCrmTools.SecurityRelated
  Assembly Version: 1.2018.9.3
  Win32 Version: 1.2018.9.3
  CodeBase: file:///C:/USERS/SMCGRATH/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SECURITYRELATED.DLL
----------------------------------------
MsCrmTools.SiteMapEditor
  Assembly Version: 1.2019.5.12
  Win32 Version: 1.2019.5.12
  CodeBase: file:///C:/USERS/SMCGRATH/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SITEMAPEDITOR.DLL
----------------------------------------
MsCrmTools.SolutionComponentsMover
  Assembly Version: 1.2016.6.3
  Win32 Version: 1.2016.6.3
  CodeBase: file:///C:/USERS/SMCGRATH/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SOLUTIONCOMPONENTSMOVER.DLL
----------------------------------------
MsCrmTools.SolutionImport
  Assembly Version: 1.2016.8.23
  Win32 Version: 1.2016.8.23
  CodeBase: file:///C:/USERS/SMCGRATH/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SOLUTIONIMPORT.DLL
----------------------------------------
MscrmTools.SyncFilterManager
  Assembly Version: 1.2017.3.1
  Win32 Version: 1.2017.3.1
  CodeBase: file:///C:/USERS/SMCGRATH/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SYNCFILTERMANAGER.DLL
----------------------------------------
MsCrmTools.Translator
  Assembly Version: 1.2018.4.6
  Win32 Version: 1.2018.4.6
  CodeBase: file:///C:/USERS/SMCGRATH/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.TRANSLATOR.DLL
----------------------------------------
MsCrmTools.UserSettingsUtility
  Assembly Version: 1.2019.6.9
  Win32 Version: 1.2019.6.9
  CodeBase: file:///C:/USERS/SMCGRATH/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.USERSETTINGSUTILITY.DLL
----------------------------------------
MsCrmTools.ViewLayoutReplicator
  Assembly Version: 1.2017.4.4
  Win32 Version: 1.2017.4.4
  CodeBase: file:///C:/USERS/SMCGRATH/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.VIEWLAYOUTREPLICATOR.DLL
----------------------------------------
MscrmTools.WebresourcesManager
  Assembly Version: 2.2019.4.7
  Win32 Version: 2.2019.4.7
  CodeBase: file:///C:/USERS/SMCGRATH/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.WEBRESOURCESMANAGER.DLL
----------------------------------------
Xrm.Sdk.PluginRegistration.Merged
  Assembly Version: 3.2019.7.1
  Win32 Version: 3.2019.07.001
  CodeBase: file:///C:/USERS/SMCGRATH/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/XRM.SDK.PLUGINREGISTRATION.DLL
----------------------------------------
System.Web
  Assembly Version: 4.0.0.0
  Win32 Version: 4.8.3928.0 built by: NET48REL1
  CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.Design
  Assembly Version: 4.0.0.0
  Win32 Version: 4.8.3761.0 built by: NET48REL1
  CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------
WindowsBase
  Assembly Version: 4.0.0.0
  Win32 Version: 4.8.3928.0 built by: NET48REL1
  CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Data
  Assembly Version: 4.0.0.0
  Win32 Version: 4.8.3761.0 built by: NET48REL1
  CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
MetadataViewProxies_0fdb6a1b-86d5-446f-a3d2-720e396b3056
  Assembly Version: 0.0.0.0
  Win32 Version: 4.8.3761.0
  CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
PresentationFramework
  Assembly Version: 4.0.0.0
  Win32 Version: 4.8.3928.0
  CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
PresentationCore
  Assembly Version: 4.0.0.0
  Win32 Version: 4.8.3928.0 built by: NET48REL1
  CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
 
************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.
 
For example:
 
<configuration>
  <system.windows.forms jitDebugging="true" />
</configuration>
 
When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by MscrmTools** [comment]
You certainly has some old SDK assemblies in your computer GAC. Please remove them
