### ISSUE TITLE
Dash in username - unable to connect

### ISSUE THREAD

**Issue by JtJammer101** [MscrmTools/MscrmTools.Xrm.Connection#98]
I have an admin account with a dash "-" in the username.  I'm unable to connect to D365 using a connection string.  Is there a way to pass the username with the dash in the connection string?  Example: admin-joe@joespizza.com

**Comment by MscrmTools** [comment]
Connection string are used as is. If something goes wrong because of the dash, I suspect that is a bug in Microsoft assemblies
